#!/usr/bin/env bash
set -euo pipefail

# changelog.sh — Generate structured CHANGELOG.md from git history
# Usage: bash changelog.sh [--tag <from-tag>] [--output CHANGELOG.md]

OUTPUT="CHANGELOG.md"
FROM_TAG=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tag) FROM_TAG="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    --help|-h) 
      echo "Usage: bash changelog.sh [--tag <from-tag>] [--output CHANGELOG.md]"
      echo ""
      echo "Generates a structured CHANGELOG.md from git commits since the last tag."
      echo ""
      echo "Options:"
      echo "  --tag <ref>      Start from a specific tag/commit instead of auto-detecting"
      echo "  --output <file>  Output file (default: CHANGELOG.md)"
      echo "  --help, -h       Show this help"
      exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# Auto-detect the last tag if not specified
if [[ -z "$FROM_TAG" ]]; then
  FROM_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
  if [[ -z "$FROM_TAG" ]]; then
    # No tags found — use the first commit
    FROM_TAG=$(git rev-list --max-parents=0 HEAD)
    echo "⚠️  No tags found. Generating changelog from the first commit."
  fi
fi

echo "📋 Generating changelog since: $FROM_TAG"
echo ""

# Get commit range
RANGE="${FROM_TAG}..HEAD"

# Parse commits into categories
ADDED=$(git log "$RANGE" --grep="^feat" --oneline --format="- %s (%h)" 2>/dev/null || true)
FIXED=$(git log "$RANGE" --grep="^fix" --oneline --format="- %s (%h)" 2>/dev/null || true)
CHANGED=$(git log "$RANGE" --grep="^chore\|^refactor\|^perf" --oneline --format="- %s (%h)" 2>/dev/null || true)
REMOVED=$(git log "$RANGE" --grep="^removed\|^remove" --oneline --format="- %s (%h)" 2>/dev/null || true)
MISC=$(git log "$RANGE" --grep="^docs\|^test\|^ci\|^build" --oneline --format="- %s (%h)" 2>/dev/null || true)

# Fallback: if no conventional commits, grab all
if [[ -z "$ADDED$FIXED$CHANGED$REMOVED$MISC" ]]; then
  echo "⚠️  No conventional commits found. Falling back to all commits."
  ALL=$(git log "$RANGE" --oneline --format="- %s (%h)")
  ADDED="$ALL"
fi

# Get version from tags
NEW_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0")
TODAY=$(date +%Y-%m-%d)

# Generate the changelog content
cat > "$OUTPUT" << EOF
# Changelog

## [${NEW_VERSION}] — ${TODAY}

EOF

has_content=false

# Helper to add a section
add_section() {
  local title="$1" content="$2"
  if [[ -n "$content" ]]; then
    has_content=true
    echo "" >> "$OUTPUT"
    echo "### ${title}" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "$content" >> "$OUTPUT"
  fi
}

add_section "✨ Added" "$ADDED"
add_section "🐛 Fixed" "$FIXED"
add_section "🔄 Changed" "$CHANGED"
add_section "🗑 Removed" "$REMOVED"
add_section "📖 Documentation / Testing" "$MISC"

if ! $has_content; then
  echo "- No significant changes in this range." >> "$OUTPUT"
fi

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "_Generated by [changelog.sh](https://github.com/CHY9213/claude-builders-bounty/tree/main/templates/changelog)_" >> "$OUTPUT"

echo ""
echo "✅ Changelog written to: $OUTPUT"
echo "   $(grep -c "^\-" "$OUTPUT" || true) entries"
